/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 makeup.gltf 
Author: DianaV.Mendoza (https://sketchfab.com/DianaV.Mendoza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/makeup-cosmetics-97038c2b5b7d44b1851ba9e33fbd20d7
Title: Makeup & Cosmetics
*/

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// import makeupScene from "./makeup.gltf";

// export default function Model(props) {
//   const { nodes, materials } = useGLTF(makeupScene)
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.pCylinder13_Black_0.geometry} material={materials.Black} />
//       <mesh geometry={nodes.pCylinder13_blinn5_0.geometry} material={materials.blinn5} />
//       <mesh geometry={nodes.pCylinder13_Iron_0.geometry} material={materials.Iron} />
//       <mesh geometry={nodes.pCylinder13_lambert1_0.geometry} material={materials.lambert1} />
//       <mesh geometry={nodes.pCylinder13_Wood_0.geometry} material={materials.Wood} />
//       <mesh geometry={nodes.pCylinder13_Blush_0.geometry} material={materials.Blush} />
//       <mesh geometry={nodes.pCylinder13_Crystal_0.geometry} material={materials.Crystal} />
//     </group>
//   )
// }

// useGLTF.preload(makeupScene)

import React from "react";
import { a } from "@react-spring/three";
import { useGLTF } from "@react-three/drei";

import makeupScene from "../assets/3d/makeup.glb";

const Makeup = ({ rotation, ...props }) => {
  const { nodes, materials, scene, animations } = useGLTF(makeupScene);
 
  return (
    // <mesh {...props} >
    //   <primitive object={scene}/>

    // </mesh>
    <a.group rotation={rotation} {...props} dispose={null} >
      <mesh
        geometry={nodes.pCylinder13_Black_0.geometry}
        material={materials.Black}
      />
      <mesh
        geometry={nodes.pCylinder13_blinn5_0.geometry}
        material={materials.blinn5}
      />
      <mesh
        geometry={nodes.pCylinder13_Iron_0.geometry}
        material={materials.Iron}
      />
      <mesh
        geometry={nodes.pCylinder13_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        geometry={nodes.pCylinder13_Wood_0.geometry}
        material={materials.Wood}
      />
      <mesh
        geometry={nodes.pCylinder13_Blush_0.geometry}
        material={materials.Blush}
      />
      <mesh
        geometry={nodes.pCylinder13_Crystal_0.geometry}
        material={materials.Crystal}
      />
    </a.group>
  );
};

export default Makeup;
